version: "3.8"

networks:
  neobank-net:

volumes:
  mysql_data:

services:
  mysql:
    image: mysql:8.0
    container_name: neobank-mysql
    restart: always
    environment:
      MYSQL_DATABASE: neobank
      MYSQL_USER: neobank_user
      MYSQL_PASSWORD: StrongBank@123
      MYSQL_ROOT_PASSWORD: Root@123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - neobank-net

  nginx:
    image: nginx:alpine
    container_name: neobank-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - neobank-net
