events {}

http {
    upstream neobank_backend {
        server neobank-blue:8080;
        server neobank-green:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://neobank_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
        }
    }
}
